name: CxOne DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read            # required for checkout + artifact upload

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      # 1) Get the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Pull image & run scan
      - name: Run Checkmarx DAST
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        run: |
          # create output folder so host user owns it
          mkdir -p "${{ github.workspace }}/test_output"

          docker pull checkmarx/dast:latest

          docker run --rm \
            --user "$(id -u):$(id -g)" \                         # run as the runner user → no permissions issues later
            -e CX_APIKEY="$CX_APIKEY" \
            -v "${{ github.workspace }}:/demo" \                 # mount repo at /demo
            checkmarx/dast:latest \
              web \
              --environment-id=894af0e2-df03-4e60-8089-233cfc161deb \
              --config=/demo/gin_juice.yaml \                    # 🎯 now in repo root
              --base-url=https://ast.checkmarx.net \
              --output=/demo/test_output \
              --timeout=10000 \
              --update-interval=10 \
              --jvm-properties=-Xmx3G \
              --log-level=info \
              --verbose \
              --retry=3 \
              --retry-delay=20 \
              --fail-on HIGH

      # 3) Upload the scan output
      - name: Archive DAST results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CxOne-DAST-Output
          path: ./test_output
          if-no-files-found: warn
