# .github/workflows/cxone-dast-api-scan-altoro-mutual.yml
name: CxONE DAST API Scan – Altoro Mutual

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # manual trigger

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare output folder
        run: |
          mkdir -p "${{ github.workspace }}/output_fold"
          sudo chown -R 1000:1000 "${{ github.workspace }}"

      - name: Checkmarx DAST GitHub Action
        uses: Checkmarx/dast-github-action@v2.3.0
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        with:
          command: "api"
          config: "./altoro_mutual.yaml"
          openapi: "./altoro_mutual.json"
          log_level: "info"
          base_url: "https://ast.checkmarx.net"
          environment_id: "0320bf69-192d-4b59-b1cf-7da4bd91d5d1"
          fail_on: ""
          verbose: true
          output: "${{ github.workspace }}/output_fold"

      - name: Restore ownership for artifacts
        if: always()
        run: sudo chown -R 1001:1001 "${{ github.workspace }}/output_fold"

      - name: Upload DAST logs and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cxone-dast-report
          path: "${{ github.workspace }}/output_fold"
