name: CxOne DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Pull the latest Checkmarx DAST image
      - name: Pull DAST image
        run: docker pull checkmarx/dast:latest

      # 3. Run the scan (root user so the container can create /demo/test_output)
      - name: Run DAST scan
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}   # set the secret as an environment variable
        run: |
          # make sure the host output folder exists
          mkdir -p "${{ github.workspace }}/test_output"

          docker run --rm \
            --user 0 \
            -e CX_APIKEY=$CX_APIKEY \
            -v ${{ github.workspace }}:/demo \
            checkmarx/dast:latest \
            web \
            --environment-id=b97d9063-cf64-4b0f-bd98-ef3caf3b451b \
            --config=/demo/zap_config_web.yaml \
            --base-url=https://ast.checkmarx.net \
            --output=/demo/test_output \
            --timeout=10000 \
            --update-interval=10 \
            --jvm-properties=-Xmx3G \
            --log-level=info \
            --verbose \
            --retry=3 \
            --retry-delay=20 \
            --fail-on HIGH

      # 4. Always upload whatever the scan wrote to /test_output
      - name: Upload DAST artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CxOne-DAST-Output
          path: ./test_output
          if-no-files-found: warn
