on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Run CxOne DAST Web Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull and Run Checkmarx DAST via Docker
        run: |
          docker pull checkmarx/dast:latest
          docker run --rm \
            -e CX_APIKEY=${{ secrets.CX_APIKEY }} \
            -v ${{ github.workspace }}:/app \
            checkmarx/dast:latest web \
            --environment-id=b97d9063-cf64-4b0f-bd98-ef3caf3b451b \
            --config=/app/gin_juice.yaml \
            --base-url=https://ast.checkmarx.net \
            --output=/app/output \
            --timeout=10000 \
            --update-interval=10 \
            --jvm-properties=-Xmx3G \
            --log-level=info \
            --verbose \
            --retry=3 \
            --retry-delay=20 \
            --fail-on HIGH

      - name: Reclaim output directory permissions
        if: always()
        run: |
          if [ -d "${{ github.workspace }}/output" ]; then
            sudo chown -R 1001:1001 "${{ github.workspace }}/output"
          fi

      - name: Upload DAST Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CxOne-DAST-Output
          path: ./output
          if-no-files-found: warn
