name: CxOne DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Checkmarx DAST
      env:
        CX_APIKEY: ${{ secrets.CX_APIKEY }}
      run: |
        set -e

        # make sure the runner owns the output folder
        OUT_DIR="${{ github.workspace }}/test_output"
        mkdir -p "$OUT_DIR"

        docker pull checkmarx/dast:latest

        docker run --rm \
          --user "$(id -u):$(id -g)" \
          -e CX_APIKEY="$CX_APIKEY" \
          -v "${{ github.workspace }}:/demo" \
          checkmarx/dast:latest \
          web \
          --environment-id=b97d9063-cf64-4b0f-bd98-ef3caf3b451b \
          --config=/demo/gin_juice.yaml \
          --base-url=https://ast.checkmarx.net \
          --output=/demo/test_output \
          --timeout=10000 \
          --update-interval=10 \
          --jvm-properties=-Xmx3G \
          --log-level=info \
          --verbose \
          --retry=3 \
          --retry-delay=20 \
          --fail-on HIGH

    - name: Archive DAST results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CxOne-DAST-Output
        path: ./test_output
        if-no-files-found: warn
