on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.3 # or latest known working version
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        with:
          command: "web"
          config: './gin_juice.yaml'
          base_url: "https://ast.checkmarx.net"
          environment_id: "b97d9063-cf64-4b0f-bd98-ef3caf3b451b"
          fail_on: "HIGH"
          verbose: true
          output: ./output

      - name: Reclaim output directory
        if: always()
        run: |
          if [ -d "${{ github.workspace }}/output" ]; then
            sudo chown -R 1001:1001 "${{ github.workspace }}/output"
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ./output
          if-no-files-found: warn
