name: CxOne DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull and run DAST (latest, root user)
        run: |
          docker pull checkmarx/dast:latest
          docker run --rm \
            --user 0 \ 
            -e CX_APIKEY=${{ secrets.CX_APIKEY }} \
            -v ${{ github.workspace }}:/demo \
            checkmarx/dast:latest \
            web \
            --environment-id=b97d9063-cf64-4b0f-bd98-ef3caf3b451b \
            --config=/demo/zap_config_web.yaml \
            --base-url=https://us.ast.checkmarx.net \
            --output=/demo/test_output \
            --timeout=10000 \
            --update-interval=10 \
            --jvm-properties=-Xmx3G \
            --log-level=info \
            --verbose \
            --retry=3 \
            --retry-delay=20 \
            --fail-on HIGH

      - name: Upload DAST artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CxOne-DAST-Output
          path: ./test_output
          if-no-files-found: warn
